import { Client, Employee, ServiceItem, PackageItem, Appointment, SaleInvoice, ExpenseItem, NotificationItem } from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'c-1',
    name: 'أحمد محمد',
    phone: '0501234567',
    initials: 'أ م',
    registeredDate: '2023-01-15',
    lastVisit: '2023-10-25',
    status: 'نشط',
    isVip: true,
    totalSpent: 1450,
    visitsCount: 12,
    preferredBarberId: 'emp-4',
    preferredBarberName: 'محمود حسن',
    preferredBarberRole: 'أخصائي شعر ولحية',
    preferredBarberImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHLPD8tjcaic-8RBak1wsJIVMjUuptQgA23sjzg1N3LBYACkG1vgici_qS56A3yxzXDuKTKrvicpA2qqAA3R-NOq-ylIf0UWIWGVBkp4fv_dGf60IGrvBcR76x9yZLKa4583tPaFBCZXtYMUt4TShjJVJFRSXzl9_pCKZuZ33ljaROIlJhH2I88G9lKkI0_928KZMOqTfykViy7FJqux36p0JNjt1-vpz-rExloGoz2NWfr_zK-9HWJw',
    visitHistory: [
      {
        id: 'vh-1',
        serviceName: 'حلاقة دقن + شعر',
        date: '2023-10-25',
        barberName: 'محمود حسن',
        price: 150,
      },
      {
        id: 'vh-2',
        serviceName: 'تنظيف بشرة ملكي',
        date: '2023-09-10',
        barberName: 'رامي كريم',
        price: 250,
      },
      {
        id: 'vh-3',
        serviceName: 'حلاقة شعر VIP + ماسك',
        date: '2023-08-14',
        barberName: 'محمود حسن',
        price: 180,
      },
    ],
  },
  {
    id: 'c-2',
    name: 'خالد عبدالله',
    phone: '0559876543',
    initials: 'خ ع',
    registeredDate: '2023-05-20',
    lastVisit: '2023-09-12',
    status: 'في موعد',
    isVip: false,
    totalSpent: 820,
    visitsCount: 7,
    preferredBarberId: 'emp-1',
    preferredBarberName: 'أحمد محمود',
    preferredBarberRole: 'حلاق محترف',
    preferredBarberImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBaOr8lAXw0GVRrxi6Kv5iC1vSSHkdoIuz0eyxXGd1YxNrP-C3u0gdPSJSl6VH1mfS8EWuiDRkA2HJjUjA4saCb0ZllpJ0nto4YOtM5uGYQ_rmFNWhiStRBBIwrwL3ZF6EAARIJKlDXHDoXtlGur8K--nPpzv2KAwAkHTqgNTDes8bZ5slfGIlupMYPqS9cBAwt3ltdfpRgVds-nq8tUCbWUawkaCYovwx1HLIqJ825rEijd3_pmTYP3g',
    visitHistory: [
      {
        id: 'vh-4',
        serviceName: 'حلاقة شعر وذقن',
        date: '2023-09-12',
        barberName: 'أحمد محمود',
        price: 120,
      },
    ],
  },
  {
    id: 'c-3',
    name: 'سالم فهد',
    phone: '0533322111',
    initials: 'س ف',
    registeredDate: '2022-11-05',
    lastVisit: '2023-01-30',
    status: 'غير نشط',
    isVip: false,
    totalSpent: 450,
    visitsCount: 4,
    preferredBarberId: 'emp-2',
    preferredBarberName: 'خالد عبدالله',
    preferredBarberRole: 'حلاق متميز',
    preferredBarberImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5TCkv7ZV-gMxkuvtyUhWrhL48rz51aeQjy3mcu_U9R8jVSHcaD351mXZQP9GPHFw-H-U4j_aGgfX4D-vgKgC2cQDPvNZ9k1Qo0ogMkk9gppJnPFityDAvbV4SdlM54DfyLSee__msT7MXNRa89zb4logBXE2UXd5xUqeMv8JjG6iEIhQtzY5KMUTxrgDhiem0XKKJFJhYddVR_FywsNjUUvgZmcpuDhwvctCdqtdF_mQtrgyFo9qC5w',
    visitHistory: [
      {
        id: 'vh-5',
        serviceName: 'حلاقة شعر + سشوار',
        date: '2023-01-30',
        barberName: 'خالد عبدالله',
        price: 70,
      },
    ],
  },
  {
    id: 'c-4',
    name: 'ياسر حسين',
    phone: '0509988776',
    initials: 'ي ح',
    registeredDate: '2023-03-10',
    lastVisit: '2023-10-24',
    status: 'نشط',
    isVip: true,
    totalSpent: 2100,
    visitsCount: 16,
    preferredBarberId: 'emp-1',
    preferredBarberName: 'أحمد محمود',
    preferredBarberRole: 'حلاق محترف',
    preferredBarberImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBaOr8lAXw0GVRrxi6Kv5iC1vSSHkdoIuz0eyxXGd1YxNrP-C3u0gdPSJSl6VH1mfS8EWuiDRkA2HJjUjA4saCb0ZllpJ0nto4YOtM5uGYQ_rmFNWhiStRBBIwrwL3ZF6EAARIJKlDXHDoXtlGur8K--nPpzv2KAwAkHTqgNTDes8bZ5slfGIlupMYPqS9cBAwt3ltdfpRgVds-nq8tUCbWUawkaCYovwx1HLIqJ825rEijd3_pmTYP3g',
    visitHistory: [
      {
        id: 'vh-6',
        serviceName: 'باقة العناية المتكاملة',
        date: '2023-10-24',
        barberName: 'أحمد محمود',
        price: 250,
      },
    ],
  },
  {
    id: 'c-5',
    name: 'طارق نور',
    phone: '0567711223',
    initials: 'ط ن',
    registeredDate: '2023-07-01',
    lastVisit: '2023-10-24',
    status: 'نشط',
    isVip: false,
    totalSpent: 900,
    visitsCount: 5,
    preferredBarberId: 'emp-4',
    preferredBarberName: 'محمود حسن',
    preferredBarberRole: 'أخصائي شعر ولحية',
    preferredBarberImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHLPD8tjcaic-8RBak1wsJIVMjUuptQgA23sjzg1N3LBYACkG1vgici_qS56A3yxzXDuKTKrvicpA2qqAA3R-NOq-ylIf0UWIWGVBkp4fv_dGf60IGrvBcR76x9yZLKa4583tPaFBCZXtYMUt4TShjJVJFRSXzl9_pCKZuZ33ljaROIlJhH2I88G9lKkI0_928KZMOqTfykViy7FJqux36p0JNjt1-vpz-rExloGoz2NWfr_zK-9HWJw',
    visitHistory: [
      {
        id: 'vh-7',
        serviceName: 'صبغة شعر + ماسك',
        date: '2023-10-24',
        barberName: 'محمود حسن',
        price: 400,
      },
    ],
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    name: 'أحمد محمد',
    role: 'Barber',
    phone: '0501234567',
    status: 'نشط',
    rating: 4.9,
    clientsCount: 124,
    servicesCount: 156,
    totalSales: 15400,
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBaOr8lAXw0GVRrxi6Kv5iC1vSSHkdoIuz0eyxXGd1YxNrP-C3u0gdPSJSl6VH1mfS8EWuiDRkA2HJjUjA4saCb0ZllpJ0nto4YOtM5uGYQ_rmFNWhiStRBBIwrwL3ZF6EAARIJKlDXHDoXtlGur8K--nPpzv2KAwAkHTqgNTDes8bZ5slfGIlupMYPqS9cBAwt3ltdfpRgVds-nq8tUCbWUawkaCYovwx1HLIqJ825rEijd3_pmTYP3g',
    permissions: {
      customers: { enabled: true, view: true, add: true, edit: true, delete: false },
      sales: { enabled: true, view: true, add: true, edit: false, cancelInvoice: false },
      staff: { enabled: false, view: false, manage: false },
    },
  },
  {
    id: 'emp-2',
    name: 'خالد عبدالله',
    role: 'Barber',
    phone: '0559876543',
    status: 'نشط',
    rating: 4.7,
    clientsCount: 98,
    servicesCount: 112,
    totalSales: 9850,
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5TCkv7ZV-gMxkuvtyUhWrhL48rz51aeQjy3mcu_U9R8jVSHcaD351mXZQP9GPHFw-H-U4j_aGgfX4D-vgKgC2cQDPvNZ9k1Qo0ogMkk9gppJnPFityDAvbV4SdlM54DfyLSee__msT7MXNRa89zb4logBXE2UXd5xUqeMv8JjG6iEIhQtzY5KMUTxrgDhiem0XKKJFJhYddVR_FywsNjUUvgZmcpuDhwvctCdqtdF_mQtrgyFo9qC5w',
    permissions: {
      customers: { enabled: true, view: true, add: true, edit: false, delete: false },
      sales: { enabled: true, view: true, add: true, edit: false, cancelInvoice: false },
      staff: { enabled: false, view: false, manage: false },
    },
  },
  {
    id: 'emp-3',
    name: 'سامر كمال',
    role: 'Cashier',
    phone: '0533221111',
    status: 'نشط',
    rating: 4.8,
    clientsCount: 140,
    servicesCount: 180,
    totalSales: 22100,
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCrIpHUrDxq6r1OAyhSqX5WT1lHK7m4RtsAFzHsH_pFThFoksyB12Y9YiaPO5B50QCCMSN_xMt1ou9b7UNqemdoVl6GG8QlhO6LP27Fu3ZpjourbnQjpfs20GpIVMkvq5ajpurLx4RGj4a6An4gWpAtDxbukvOLc1hiziqH2xnwNttJUyZYSsXbeEt_pGPlHlrONH3KsJM4lzbJixtmuncVAgIL_kzBaKlLl1PHpzwuf_d72OAOfcaUzg',
    permissions: {
      customers: { enabled: true, view: true, add: true, edit: true, delete: false },
      sales: { enabled: true, view: true, add: true, edit: true, cancelInvoice: true },
      staff: { enabled: false, view: true, manage: false },
    },
  },
  {
    id: 'emp-4',
    name: 'محمود حسن',
    role: 'Manager',
    phone: '0566778899',
    status: 'نشط',
    rating: 4.95,
    clientsCount: 160,
    servicesCount: 210,
    totalSales: 31200,
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA-2EHHjCngBDkuODKpAc2KsKVjiCL-m8hBpu1pJLSojQbX4xuxCh4GX8OnUd-XERS1fdOGyKchqDeuvR2lvObrW9gmKgkEddiHg0u5Bvd4rsTMfINPgf81zVbUAKNWW9C7CYjV0Zz68lzjQKbUwU4JiWa0Fh831e5RQjHyb2bm0HML7sWoKVu2irXQymXK-Tx52jk8JTsaBYHqNhE9cMTbAk-FezraMbP4A59VQ_OFGK77zIb5RkWDdw',
    permissions: {
      customers: { enabled: true, view: true, add: true, edit: true, delete: true },
      sales: { enabled: true, view: true, add: true, edit: true, cancelInvoice: true },
      staff: { enabled: true, view: true, manage: true },
    },
  },
  {
    id: 'emp-5',
    name: 'عمر سليمان',
    role: 'Barber',
    phone: '0544112233',
    status: 'نشط',
    rating: 4.8,
    clientsCount: 110,
    servicesCount: 130,
    totalSales: 11200,
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA5NR1krJV7fsTHv5UEZ-C76x9UQtV8uk_5bvv-zZrAV7K95e3ScS_CpD1v9Os672Pg_kZsuHIIf6eGPRb8-mjBVt71SIwQ1VDk75rONIFZqoryeNV4rj9mQqvD1896zIkuOEdHQyQZiyQYOXCHnZPr8dWgojlW_RK0x-9vasQyn6iI6aAy-OHxsLtmuJBZvBf-GsavFdKRrYRM2BKaS3T5FRBkOZmnWET7VyIUvhWhRmsM8tddErm9BA',
    permissions: {
      customers: { enabled: true, view: true, add: true, edit: false, delete: false },
      sales: { enabled: true, view: true, add: true, edit: false, cancelInvoice: false },
      staff: { enabled: false, view: false, manage: false },
    },
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 's-1',
    name: 'حلاقة شعر',
    price: 50,
    duration: 30,
    category: 'الخدمات',
    icon: 'content_cut',
    borderAccent: '#79591d',
    description: 'قص شعر احترافي وتدريج كلاسيكي أو عصري',
  },
  {
    id: 's-2',
    name: 'حلاقة ذقن',
    price: 35,
    duration: 20,
    category: 'الخدمات',
    icon: 'face',
    borderAccent: '#79591d',
    description: 'تحديد وتشذيب اللحية مع منشفة دافئة',
  },
  {
    id: 's-3',
    name: 'حلاقة شعر + ذقن VIP',
    price: 80,
    duration: 50,
    category: 'الخدمات',
    icon: 'spa',
    borderAccent: '#79591d',
    description: 'حلاقة متكاملة للشعر واللحية مع مساج ومنشفة ساخنة',
  },
  {
    id: 's-4',
    name: 'حلاقة أطفال',
    price: 40,
    duration: 30,
    category: 'الخدمات',
    icon: 'child_care',
    borderAccent: '#059669',
    description: 'حلاقة لطيفة وآمنة للأطفال',
  },
  {
    id: 's-5',
    name: 'فوطة ساخنة / مساج رأس',
    price: 20,
    duration: 15,
    category: 'الإضافات',
    icon: 'hot_tub',
    borderAccent: '#059669',
    description: 'جلسة استرخاء بفوطة عطرية ساخنة ومساج فروة الرأس',
  },
  {
    id: 's-6',
    name: 'صبغة شعر',
    price: 120,
    duration: 45,
    category: 'الخدمات',
    icon: 'palette',
    borderAccent: '#D97706',
    description: 'صبغة كاملة أو خصلات بأعلى درجات الجودة',
  },
  {
    id: 's-7',
    name: 'صبغة ذقن',
    price: 60,
    duration: 30,
    category: 'الخدمات',
    icon: 'format_paint',
    borderAccent: '#D97706',
    description: 'تلوين اللحية طبيعياً وإخفاء الشيب',
  },
  {
    id: 's-8',
    name: 'تنظيف بشرة عميق',
    price: 150,
    duration: 40,
    category: 'الإضافات',
    icon: 'face_retouching_natural',
    borderAccent: '#79591d',
    description: 'إزالة الرؤوس السوداء وتقشير وماسك ترطيب',
  },
  {
    id: 's-9',
    name: 'شمع الأنف والأذن',
    price: 25,
    duration: 10,
    category: 'الإضافات',
    icon: 'auto_fix_high',
    borderAccent: '#059669',
    description: 'تنظيف شمعي سريع وآمن',
  },
  {
    id: 's-10',
    name: 'زيت لحية فاخر',
    price: 85,
    duration: 0,
    category: 'منتجات العناية',
    icon: 'sanitizer',
    borderAccent: '#79591d',
    description: 'مستخلص الزيوت الطبيعية لترطيب اللحية',
  },
  {
    id: 's-11',
    name: 'واكس تصفيف شعر مات',
    price: 65,
    duration: 0,
    category: 'منتجات العناية',
    icon: 'shopping_bag',
    borderAccent: '#79591d',
    description: 'تثبيت قوي مع لمسة طبيعية غير لامعة',
  },
];

export const INITIAL_PACKAGES: PackageItem[] = [
  {
    id: 'pkg-1',
    name: 'باقة العريس المميزة',
    price: 700,
    type: 'groom',
    isPopular: true,
    isActive: true,
    features: [
      'حلاقة شعر وتدريج',
      'تشذيب وتحديد اللحية',
      'تنظيف بشرة عميق',
      'تصفيف وتثبيت',
      'ماسك الكولاجين والذهب',
      'مساج رقبة ورأس ملكي',
    ],
  },
  {
    id: 'pkg-2',
    name: 'الباقة الملكية',
    price: 1200,
    type: 'groom',
    isPopular: false,
    isActive: false,
    features: [
      'حلاقة شعر VIP',
      'صبغة لحية',
      'ماسك ذهب',
      'مساج رأس كامل',
      'جلسة حمام مغربي رجالي',
      'باديكير ومنيكير متكامل',
    ],
  },
  {
    id: 'pkg-3',
    name: 'باقة النخبة الأسبوعية',
    price: 280,
    type: 'standard',
    isPopular: true,
    isActive: true,
    features: [
      'حلاقة شعر كلاسيكية',
      'تحديد اللحية بالمنشفة الساخنة',
      'غسيل وسشوار',
      'ماسك طيني منشط',
    ],
  },
  {
    id: 'pkg-4',
    name: 'باقة العناية المتكاملة',
    price: 350,
    type: 'standard',
    isPopular: false,
    isActive: true,
    features: [
      'حلاقة شعر وذقن',
      'تنظيف بشرة بالبخار',
      'شمع أنف وأذنين',
      'مساج للكتفين والرأس',
    ],
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    clientName: 'أحمد محمد',
    clientPhone: '0501234567',
    barberId: 'emp-1',
    barberName: 'أحمد محمد',
    serviceName: 'حلاقة شعر + ذقن',
    time: '10:00',
    period: 'AM',
    date: '2023-10-24',
    status: 'جاري الآن',
    price: 80,
    icon: 'content_cut',
  },
  {
    id: 'apt-2',
    clientName: 'محمود علي',
    clientPhone: '0551122334',
    barberId: 'emp-2',
    barberName: 'خالد عبدالله',
    serviceName: 'تنظيف بشرة',
    time: '11:30',
    period: 'AM',
    date: '2023-10-24',
    status: 'قادم',
    price: 150,
    icon: 'face',
  },
  {
    id: 'apt-3',
    clientName: 'خالد سعد',
    clientPhone: '0534455667',
    barberId: 'emp-1',
    barberName: 'أحمد محمد',
    serviceName: 'حلاقة أطفال',
    time: '09:00',
    period: 'AM',
    date: '2023-10-24',
    status: 'مكتمل',
    price: 40,
    icon: 'content_cut',
  },
  {
    id: 'apt-4',
    clientName: 'محمد عبدالله',
    clientPhone: '0509988112',
    barberId: 'emp-1',
    barberName: 'أحمد محمد',
    serviceName: 'حلاقة شعر وذقن',
    time: '10:00',
    period: 'ص',
    date: '2023-11-06',
    status: 'مؤكد',
    price: 80,
    icon: 'content_cut',
  },
  {
    id: 'apt-5',
    clientName: 'سالم الدوسري',
    clientPhone: '0567788990',
    barberId: 'emp-2',
    barberName: 'خالد عبدالله',
    serviceName: 'تنظيف بشرة',
    time: '11:30',
    period: 'ص',
    date: '2023-11-06',
    status: 'قيد الانتظار',
    price: 150,
    icon: 'dry_cleaning',
  },
  {
    id: 'apt-6',
    clientName: 'عمر الفهد',
    clientPhone: '0543322119',
    barberId: 'emp-1',
    barberName: 'أحمد محمد',
    serviceName: 'حلاقة أطفال',
    time: '09:00',
    period: 'ص',
    date: '2023-11-06',
    status: 'مكتمل',
    price: 40,
    icon: 'content_cut',
  },
];

export const INITIAL_INVOICES: SaleInvoice[] = [
  {
    id: 'inv-12',
    invoiceNumber: 'INV-0012',
    date: '2023-10-24',
    timestamp: '14 Nov, 10:45 AM',
    clientName: 'ياسر حسين',
    clientPhone: '0509988776',
    barberId: 'emp-1',
    barberName: 'كريم',
    items: [
      { id: 's-3', name: 'حلاقة شعر + ذقن VIP', price: 80, quantity: 1 },
      { id: 's-8', name: 'تنظيف بشرة عميق', price: 150, quantity: 1 },
      { id: 's-5', name: 'فوطة ساخنة', price: 20, quantity: 1 },
    ],
    subtotal: 250,
    discount: 0,
    tax: 0,
    total: 250,
    paymentMethod: 'cash',
    status: 'مدفوع',
  },
  {
    id: 'inv-11',
    invoiceNumber: 'INV-0011',
    date: '2023-10-24',
    timestamp: '14 Nov, 09:30 AM',
    clientName: 'سامر كمال',
    clientPhone: '0533221111',
    barberId: 'emp-1',
    barberName: 'أحمد',
    items: [
      { id: 's-6', name: 'صبغة شعر', price: 120, quantity: 1 },
      { id: 's-7', name: 'صبغة ذقن', price: 60, quantity: 1 },
    ],
    subtotal: 180,
    discount: 0,
    tax: 0,
    total: 180,
    paymentMethod: 'card',
    status: 'مدفوع',
  },
  {
    id: 'inv-10',
    invoiceNumber: 'INV-0010',
    date: '2023-10-24',
    timestamp: '13 Nov, 08:15 PM',
    clientName: 'طارق نور',
    clientPhone: '0567711223',
    barberId: 'emp-1',
    barberName: 'كريم',
    items: [
      { id: 'pkg-4', name: 'باقة العناية المتكاملة', price: 350, quantity: 1 },
      { id: 's-1', name: 'حلاقة شعر إضافية', price: 50, quantity: 1 },
    ],
    subtotal: 400,
    discount: 0,
    tax: 0,
    total: 400,
    paymentMethod: 'wallet',
    status: 'آجل',
  },
];

export const INITIAL_EXPENSES: ExpenseItem[] = [
  {
    id: 'exp-1',
    title: 'شراء مستلزمات حلاقة وزيوت',
    category: 'مستلزمات',
    amount: 320,
    date: '2023-10-24',
    notes: 'شامبوهات ومناشف معقمة',
  },
  {
    id: 'exp-2',
    title: 'صيانة ماكينات الحلاقة',
    category: 'صيانة',
    amount: 180,
    date: '2023-10-23',
    notes: 'تغيير شفرات وتنظيف',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'موعد جديد مؤكد',
    description: 'تم تأكيد موعد للعميل أحمد محمد الساعة 10:00 ص',
    time: 'منذ 5 دقائق',
    isRead: false,
    type: 'appointment',
  },
  {
    id: 'notif-2',
    title: 'عملية بيع جديدة #INV-0012',
    description: 'تم إصدار فاتورة بقيمة 250 ج.م للعميل ياسر حسين',
    time: 'منذ 15 دقيقة',
    isRead: false,
    type: 'sale',
  },
  {
    id: 'notif-3',
    title: 'تنبيه انتهاء مخزون',
    description: 'واكس تصفيف الشعر قارب على النفاد (متبقي 3 قطع)',
    time: 'منذ ساعتين',
    isRead: true,
    type: 'system',
  },
];
